name: Bug Report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please provide enough detail to reproduce and debug quickly.
  - type: input
    id: version
    attributes:
      label: Version/Commit
      description: Tag, branch, or commit SHA
      placeholder: v0.1.0 or abc1234
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, compiler, and CMake version
      placeholder: Ubuntu 24.04, gcc 13, CMake 3.28
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
