name: Feature Request
description: Suggest an enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behavior or API
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other options you evaluated
    validations:
      required: false
  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: Why this matters for users/operators
    validations:
      required: false
